---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: pr-devops-toolkit-7
  namespace: argocd
spec:
  destination:
    namespace: pr-devops-toolkit-7
    server: https://kubernetes.default.svc
  project: previews
  source:
    helm:
      values: |
        image:
          repository: vfarcic/devops-toolkit
          tag: pr-7-31f5f17
        ingress:
          host: pr-devops-toolkit-7.devopstoolkitseries.com
      version: v3
    path: helm
    repoURL: https://github.com/vfarcic/devops-toolkit.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
